# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sigmoidc <- function(x) {
    .Call('_slise_sigmoidc', PACKAGE = 'slise', x)
}

log_sigmoidc <- function(x) {
    .Call('_slise_log_sigmoidc', PACKAGE = 'slise', x)
}

loss_smooth_c <- function(alpha, data, response, epsilon, beta, lambda1, lambda2, weight) {
    .Call('_slise_loss_smooth_c', PACKAGE = 'slise', alpha, data, response, epsilon, beta, lambda1, lambda2, weight)
}

loss_smooth_c_dc <- function(xs, dcptr) {
    .Call('_slise_loss_smooth_c_dc', PACKAGE = 'slise', xs, dcptr)
}

loss_smooth_grad_c <- function(alpha, data, response, epsilon, beta, lambda1, lambda2, weight) {
    .Call('_slise_loss_smooth_grad_c', PACKAGE = 'slise', alpha, data, response, epsilon, beta, lambda1, lambda2, weight)
}

loss_smooth_grad_c_dc <- function(xs, dcptr) {
    .Call('_slise_loss_smooth_grad_c_dc', PACKAGE = 'slise', xs, dcptr)
}

lg_combined_smooth_c_dc <- function(xs, dcptr) {
    .Call('_slise_lg_combined_smooth_c_dc', PACKAGE = 'slise', xs, dcptr)
}

lg_getgrad_c_dc <- function(xs, dcptr) {
    .Call('_slise_lg_getgrad_c_dc', PACKAGE = 'slise', xs, dcptr)
}

loss_smooth_c_ptr <- function() {
    .Call('_slise_loss_smooth_c_ptr', PACKAGE = 'slise')
}

loss_smooth_grad_c_ptr <- function() {
    .Call('_slise_loss_smooth_grad_c_ptr', PACKAGE = 'slise')
}

